# THIS SCRIPT IS FOR WHEN USING AI, THUS THE AI TAG AND PARAMETER BUT THIS CAN ALSO BE USED FOR THE SIMPLE 
# MOTION DETECTION
#
# Read and replace !
#
# /path/to = where you want the Base64Image to be generated and grabbed. You can replace the naming as well
#
# You can replace the curl headers as well just don't forget the Authorization Header

TOKEN="<add your token here, generated by ntfy>"

TIME=$1
AI=$2
BASE64IMAGE=$3
NAME=$4

echo ${BASE64IMAGE} > /path/to/base64img_${TIME}.jpg
base64 --decode /path/to/base64img_${TIME}.jpg > /path/to/base64imgd_${TIME}.jpg
curl \
-T /path/to/base64imgd_${TIME}.jpg \
-H "Filename: ${NAME}_${TIME}.jpg" \
-H "Authorization: Bearer ${TOKEN}" \
-H "Title: ${AI} Detected at the ${NAME}" \
<Add URL to your topic>
